name: Azure Pipelines

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

# ToDo: Replace the agent pool name, if you are using Udacity Cloud lab. 
# Otherwise comment out the line below. 
pool: myAgentPool

variables:
  python.version: '3.7.6'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1804
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 0.12.24
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terrafom init'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/EnsuringQualityReleases/terraform/environments/test'
        backendServiceArm: 'Azure subscription 1(692fcab2-2058-4429-b839-e86f873cdf50)'  
        backendAzureRmResourceGroupName: 'tstate'
        backendAzureRmStorageAccountName: tstate1262321534
        backendAzureRmContainerName: tstate
        backendAzureRmKey: test.terraform.tfstate
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: '192.168.1.89 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8grKjrrqx9hIL5BHaBqR/C/H2Y3f8LO0QzEVeDlkNaxijRkhi7x3EX5vtKYAv7Z5A3quVhM876hIZgvFBSNXFbfOFSMulYWa2eKxUoRbzQUuWUuRRgdl4XazFem9aont4qmB956wfTz6FX/R6++4VCiPjYBVq6IGpFgqjj80U7l1CImJVyTplaBKkNQVlFVFAPGVO2pLQdq1K882jIlOtlzfF/GD/9SWXcDZI8ykXBkNACgNl8Gfr5qkje5TJNOBSsW33c5MlgrbtI0FWJv/890XQUPwYFFu79pYhv4pDGC576hVo4GGYQXe1a36FgYHyJyXKCkCMzZb4QqVwjagd'
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv13g8O2VAujAz19wuj8m6pf5GnqJQKoNdar2TDRFgkNptcdwVVo+b1onBdP8ObJxd4CurA3o/txS5gOcQwrLJARDjoeUgdcYc5C+uk6/TyMusZe8o/GkvWVceTcpR4ZbXYQBYdYz0i3BlvEF7dJSyHAe3OttIcCGszAkLaKiTYHV8vt+R9FPgDtPJxNFaM+NyjZ9ZUpx0zwdIMIqywAmZmW1ssUKSYMB1qLhMSLdnTwJGUY2HKaufOXgRWkH/ekqg98CnNTOxzBXK4Gcj99Jw7KsNuSt6JMieREtJObogcYXavIlss6xWtmAgoYZ7Io4GS/yYuaTKDye956eh7wKx The Rig@The-Rig Ensuringqualityreleases123'
        sshKeySecureFile: 'id_rsa'
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      displayName: 'Terrafom apply'
      inputs:
        command: apply
        workingDirectory: '$(System.DefaultWorkingDirectory)/EnsuringQualityReleases/terraform/environments/test'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'Azure subscription 1(692fcab2-2058-4429-b839-e86f873cdf50)'
        backendServiceArm: 'Azure subscription 1(692fcab2-2058-4429-b839-e86f873cdf50)'  
        backendAzureRmResourceGroupName: 'tstate'
        backendAzureRmStorageAccountName: tstate1262321534
        backendAzureRmContainerName: tstate
        backendAzureRmKey: test.terraform.tfstate
