name: Azure Pipelines

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

# ToDo: Replace the agent pool name, if you are using Udacity Cloud lab. 
# Otherwise comment out the line below. 
pool: myAgentPool

variables:
  python.version: '3.7.6'
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: 'myServiceConnection'

stages:
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
    # Install Terraform on the pipeline agent 
    - task: TerraformInstaller@0
      displayName: 'Terrafom installation'
      inputs:
        terraformVersion: '0.12.24'
    
    # Run Terraform Init on the pipeline agent 
    # ToDo: Replace the resource group name, storage account name, and container name below
    - task: TerraformTaskV3@3
      displayName: 'Terrafom init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'myServiceConnection'
        backendAzureRmResourceGroupName: 'Azuredevops'
        backendAzureRmStorageAccountName: 'tfstate281845088'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'test.terraform.tfstate'
    - task: TerraformTaskV3@3
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'

    # Install SSH Key on the agent to be used by the Terraform
    # ToDo: Replace the IP and SSH public key below                    
    - task: InstallSSHKey@0
      displayName: Install SSH Key
      inputs:
        knownHostsEntry: '13.90.102.168 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNAA8UYYtNaf1MZdLVxebyZa4mcmqCQHqf/UD3vFek6aT449lC+4LMfKALnD+suG2sgEsgjbPEZoppYiHBYGJhoRUQvHz2G1J39luUDkz/JwGSXiULSPdYQ77g7nDN19I0OeQNxNiCtU/kGC+8FQ8Xb44TrxeeY9h9OYctzPvqNbq16Cf395iy0hx8zFBTqbeBIifHiEGsPtAW8xFKS7LeSd0JZKPlIwRMoVLrg8gdH8eiiQ9+E4D1/1cMxftkBTiFJTYJB1ifUmuejU3CRlpI3vGc/+puI5G5fMpOUSBlp2OyhQlCVWNkMojbhlluYUEYqEJf/96rmtmNNUbP6Loch0nMvehKpLHUD6l1qlWso2wH2Nw7YWR53rVvGrTQyRqFB98mLYxN4LAY15UPfL6ZAGRltq6xljkTfxtq5k7njhfnG4JjEtGyl47/h18P9yhurD+mc8I3Ou+996Tqt+GIovQvxqTFg+kjqL1psl31WZ9rqAMmSAIep0hra35dEu8='
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNAA8UYYtNaf1MZdLVxebyZa4mcmqCQHqf/UD3vFek6aT449lC+4LMfKALnD+suG2sgEsgjbPEZoppYiHBYGJhoRUQvHz2G1J39luUDkz/JwGSXiULSPdYQ77g7nDN19I0OeQNxNiCtU/kGC+8FQ8Xb44TrxeeY9h9OYctzPvqNbq16Cf395iy0hx8zFBTqbeBIifHiEGsPtAW8xFKS7LeSd0JZKPlIwRMoVLrg8gdH8eiiQ9+E4D1/1cMxftkBTiFJTYJB1ifUmuejU3CRlpI3vGc/+puI5G5fMpOUSBlp2OyhQlCVWNkMojbhlluYUEYqEJf/96rmtmNNUbP6Loch0nMvehKpLHUD6l1qlWso2wH2Nw7YWR53rVvGrTQyRqFB98mLYxN4LAY15UPfL6ZAGRltq6xljkTfxtq5k7njhfnG4JjEtGyl47/h18P9yhurD+mc8I3Ou+996Tqt+GIovQvxqTFg+kjqL1psl31WZ9rqAMmSAIep0hra35dEu8='
        sshKeySecureFile: 'id_rsa'
